version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email {email} -d {domain} --agree-tos
  
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - mysql.env
    volumes:
      - mysql:/var/lib/mysql
  
  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    env_file:
      - wordpress.env 
    volumes:
      - wordpress:/var/www/html
  
  frontend:
    image: ghcr.io/bkode-vn/ccp-frontend:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - frontend.env


volumes:
  mysql:
  wordpress:
