version: '3.8'

services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: JRAMaTGN6T4DzH
      MYSQL_ROOT_PASSWORD: yHcRDv841GXZc
    volumes:
      - db:/var/lib/mysql
  
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: JRAMaTGN6T4DzH
      WORDPRESS_DB_NAME: wp
    volumes:
      - wordpress:/var/www/html
  
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    command: npm run dev
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    env_file:
      - ./frontend/.env.local
    volumes:
      - ./frontend:/app


volumes:
  db:
  wordpress:
