version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html:delegated
  
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: JRAMaTGN6T4DzH
      MYSQL_ROOT_PASSWORD: yHcRDv841GXZc
    volumes:
      - mysql:/var/lib/mysql:delegated
  
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated
  
  wp:
    build:
      context: .
      dockerfile: php.dockerfile
    entrypoint: ['wp', '--allow-root']
    volumes:
      - ./wordpress:/var/www/html:delegated
  
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    env_file:
      - ./frontend/.env.local


volumes:
  mysql:
